### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ExtraBytez** [leoetlino/byml-v2#14]
C:\Users\!!!\AppData\Local\bcml\mods\0103_MinimumValidBNP\content\Actor>byml_to_yml dummy.byml dummy.yml
Traceback (most recent call last):
  File "c:\users\!!!\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\!!!\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\!!!\AppData\Local\Programs\Python\Python38\Scripts\byml_to_yml.exe\__main__.py", line 7, in <module>
  File "c:\users\!!!\appdata\local\programs\python\python38\lib\site-packages\byml\byml_to_yml.py", line 26, in main
    root = byml.Byml(data).parse()
  File "c:\users\!!!\appdata\local\programs\python\python38\lib\site-packages\byml\byml.py", line 67, in __init__
    raise ValueError("Invalid magic: %s (expected 'BY' or 'YB')" % magic)
ValueError: Invalid magic: b'' (expected 'BY' or 'YB')

C:\Users\!!!\AppData\Local\bcml\mods\0103_MinimumValidBNP\content\Actor>

**Comment by leoetlino** [comment]
This is most certainly user error - the error message indicates that you are trying to parse something that is not actually a BYML as if it were a BYML.

If you think this is incorrect, please upload your dummy.byml file and I can take another look.
