### ISSUE TITLE
--version -V errors

### ISSUE THREAD

**Issue by HGStone** [leoetlino/byml-v2#15]
Hello, when trying to use yml_to_byml and the --version or -V arguments I am met with this error.

`
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Scripts\yml_to_byml.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\byml\yml_to_byml.py", line 27, in main
    byml.Writer(root, be=args.be, version=args.version).write(buf)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\byml\byml.py", line 234, in __init__
    if not (1 <= version <= 4):
TypeError: '<=' not supported between instances of 'int' and 'str'
`

**Comment by ArchLeaders** [comment]
What did you provide as the version string?

**Comment by HGStone** [comment]
I tried 1 2 3 and 4

**Comment by ArchLeaders** [comment]
Hm odd, I thought python automatically cast int-like strings. Seems like an issue with the script though.

**Comment by leoetlino** [comment]
17770f9d34f09a3d8f9e982120537c4d287c2e43 should fix this. Update to v2.4.3 to get the fix.
