### ISSUE TITLE
yml_to_byml does not support empty documents

### ISSUE THREAD

**Issue by davidzchen** [leoetlino/byml-v2#21]
According to the [documentation](https://zeldamods.org/wiki/BYML#Header) on ZeldaMods, empty BYML documents are supported. In this case, the offset to root node would be 0 if the document is completely empty.

However, `yml_to_byml` throws an error when the input YAML document is empty:

```
$ touch empty.yml
$ yml_to_byml empty.yml ./empty.byml
Traceback (most recent call last):
  File "/Users/dzc/.local/venv/bin/yml_to_byml", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/dzc/.local/venv/lib/python3.12/site-packages/byml/yml_to_byml.py", line 27, in main
    byml.Writer(root, be=args.be, version=args.version).write(buf)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dzc/.local/venv/lib/python3.12/site-packages/byml/byml.py", line 232, in __init__
    raise ValueError("Data should be a dict or a list")
ValueError: Data should be a dict or a list
```

**Comment by leoetlino** [comment]
Sounds easy to fix - we should relax the "data should be dict or list" check to also allow None.
