### ISSUE TITLE
DLL load failed while importing syaz0

### ISSUE THREAD

**Issue by EastWinds1991** [leoetlino/byml-v2#6]
Please let me preface this by saying that i am totally new to the world of modding and programming in general, so any instruction on what else i need to provide will be appreciated.

I have tried to install byml-v2 on 4 PC's currently, 2 being frequently used systems, and 2 being brand new installs that i have only installed 2 to 3 days ago.

when i try to convert Breath of the Wilds ActorInfo.Product.sbyml to a yml i receive the error 

Traceback (most recent call last):
  File "c:\users\scc\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\scc\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\SCC\AppData\Local\Programs\Python\Python38\Scripts\byml_to_yml.exe\__main__.py", line 4, in <module>
  File "c:\users\scc\appdata\local\programs\python\python38\lib\site-packages\byml\byml_to_yml.py", line 8, in <module>
    import syaz0
ImportError: DLL load failed while importing syaz0: The specified module could not be found.

Please help

**Comment by leoetlino** [comment]
You need the Visual C++ 2019 redistributables. You can find them here: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by EastWinds1991** [comment]
thank you for your help
